version: '3'
services:
  nginx:
    image: nginx
    restart: 'always'
    ports:
            - "80:80"
    container_name: nginx-container
    networks:
      static-network:
        ipv4_address: 172.20.128.2
  proxy:
    image: proxy
    restart: 'always'
    ports:
            - "8080:8080"
    container_name: proxy-container
    networks:
      static-network:
        ipv4_address: 172.20.128.3
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16